Create Create A Unique Email For Membership Renewals in PMPro
strangerstudios/pmpro-snippets-library pull request #225
Opened 2024-11-18 17:11 UTC by MaryOJob

…ips Pro

2025-01-27 14:23 UTC, andrewlimaza requested changes
Requires WPCS and correct docblock layout.  A nice to have might be a fallback if the file doesn't exist in the email directory to use default text so it doesn't break completely or send empty emails.

Please can you make these adjustments.

2025-01-29 15:19 UTC, MaryOJob commented
@andrewlimaza I updated this snippet, wanted to ask too; should we still be adding custom email templates like this or this should be done using the `pmproet_templates` filter?

2025-01-30 09:46 UTC, andrewlimaza commented
Yes it would be best to add it to the `pmproet_templates` filter and the linked documentation would need to be updated (once merged in).

2025-02-04 21:59 UTC, MaximilianoRicoTabo commented
Hey @andrewlimaza @MaryOJob what do you think about hooking into
`pmpro_send_checkout_emails` filter https://github.com/strangerstudios/paid-memberships-pro/blob/v3.4/includes/checkout.php#L299

and then instead of send the checkout email instantiate a new custom renewal class created as a child of PMPro_Email_Template  class and send it. A more v3.4 approach. I can test further tomorrow if you think it worths

2026-03-09 10:11 UTC, andrewlimaza commented
We are bringing out liquid templates for more conditional logic. This is no longer needed.

2026-03-09 10:11 UTC, closed without merging